version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: iziplan_db
    environment:
      MYSQL_ROOT_PASSWORD: iziplan_db
      MYSQL_DATABASE: iziplan_db
      MYSQL_USER: iziplan_db
      MYSQL_PASSWORD: iziplan_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: